# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title                   : KPA
email                   : 123@email.com
description             : >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username        : username
github_username         : username
minimal_mistakes_skin   : air
search                  : true
name                    : "KPA"
#og_image                : "/assets/images/logo.png"  # Skal være min 120*120 og max 1 MB

# Build settings
markdown                : kramdown
remote_theme            : mmistakes/minimal-mistakes

# Outputting
permalink               : /:categories/:year/:month/:title/
paginate                : 10 # amount of posts to show
paginate_path           : /page:num/
timezone                : Europe/Copenhagen
locale                  : "da-DK"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "KPA author name"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""


footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      date_format: "%-d. %b %Y"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Prose.io
prose:
  rooturl: '_posts'
  #siteurl: 'http://prose.github.io/starter/'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Kort beskrivelse"
          help: "Skriv evt. en kort beskrivelse/teaser for indlægget (ikke alt for langt)."
      - name: "date"
        field:
          element: "text"
          label: "Dato"
          help: "Format: YYYY-MM-DD. Skal angives."
          value: CURRENT_DATETIME
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tilføj nøgleord"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
